# set this to your own
export S3_BUCKET=
export S3_BUCKET_REGION=
export AGENT_KEY=
export TFLOW_AGENT_KEY=
export YOUR_VIRTUAL_CLUSTER_ID=
export CLUSTER_REGION=
export WARPSTREAM_DEFAULT_VIRTUAL_CLUSTER_ID=

